### ISSUE TITLE
[the standard answer may be wrong]

### ISSUE THREAD

**Issue by cnxhwy** [Go-zh/tour#190]
上下文: /flowcontrol/7

请描述要汇报的问题，如果可能的话请附上源代码
the answer should be like this
9  27 >= 20
20

but the answer is like this
![image](https://cloud.githubusercontent.com/assets/5432968/8054205/7b069a52-0ec9-11e5-8082-0159eecad2e4.png)

**Comment by minux** [comment]
结果是正确的。因为在调用一个函数前所有的参数都必须先被求值，所以两个Pow函数调用完了之后fmt.Println才会开始执行。

**Comment by cnxhwy** [comment]
Right！I ignore the two functions were act as parameters;
