### ISSUE TITLE
slice 练习的翻译修改建议

### ISSUE THREAD

**Issue by anamewing** [Go-zh/tour#191]
上下文: /moretypes/14
翻译修改建议：

实现 Pic 。它应当返回一个 长度为 dy 的 slice ，该 slice 中每个元素为长度为 dx 的 8 位无符号整数 slice 。当执行这个程序，它会将整数转换为灰度（好吧，蓝度）图片进行展示。 

图片的选择取决于你。有趣的函数包括 (x+y)/2、x*y 和 x^y （使用 math.Pow 计算最后的函数）。 

 （需要使用循环来分配 [][]uint8 中的每个 []uint8 。）

（使用 uint8(intValue) 在类型之间进行转换。）

**Comment by OlingCat** [comment]
0.0 谢谢喵呜酱~！
其实整个 tour 是打算重译的，原来的版本一直不大满意，不过因为拖延症就一直坑着= =||

**Comment by OlingCat** [comment]
时隔近一年= =||
要不要审校一下0.0？
