### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by gmsft** [Go-zh/tour#193]
上下文: /welcome/3

请描述要汇报的问题，如果可能的话请附上源代码
***********************以下为问题反馈******************************************
文中写道：
在 Playground 中，时间从 2009-11-10 23:00:00 UTC（了解这个日期的重要含义是留给读者的练习）。给程序赋确定性的输出使得缓存程序的输出变得容易。
原文：
In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.
感觉有两处翻译是不是翻译成如下更好：
1、时间开始于2009
2、给程序赋于确定性的输出使得缓存程序更容易

**Comment by minux** [comment]
谢谢，我觉得重新翻译成这样比较好，你觉得如何？

在 Playground 中，时间总是从 UTC 2009年11月10日 23点整开始（了解这个时间的重要含义是留给读者的练习）。
这样给程序赋予确定性的输出也有利于缓存程序的输出。

**Comment by gmsft** [comment]
恩。这样可以。读起来顺畅，也好理解。谢谢你。
