### ISSUE TITLE
为什么要用 Cherry Pick 取代 Merge？

### ISSUE THREAD

**Issue by qiansen1386** [Go-zh/tour#207]
官方要求必须用摘樱桃么？这么“洁癖”是几个意思？这样对贡献者公平？这是 github 的正确使用方式么？

**Comment by OlingCat** [comment]
首先官方是有洁癖，不过也是因为他们是在 Gerrit 上 review 的，单条线容易跟踪变化，发行注记也好写。我们 cherry-pick 则是为了让我们的 Gerrit 同步容易，避免麻烦（很麻烦= =||）。贡献者的名字会作为Commiter，并没有什么不公平的。至于我们放到 Github 则主要是便于让大家获取源码，提交和修改还是在 Gerrit 上进行。
至于如何参与的问题....这是我的锅，相关文档还没有完善，敬请见谅= =||

**Comment by qiansen1386** [comment]
@OlingCat  不要紧……

**Comment by qiansen1386** [comment]
@OlingCat 哪里有Commiter????能方便告知一下么？

**Comment by qiansen1386** [comment]
说句题外话，看起来小组的 [Gerrit Code Review](review.go-zh.org)很好用啊，有什么需要帮忙的怎么看啊？我们有权提交新的 changes 么？还是最好直接提交给Google？

**Comment by OlingCat** [comment]
这个..你可以翻译新的文档或blog，具体指南可以看草稿版的https://docs.google.com/document/d/1KM5R-vjvQfLLyK3VtzALiMlXoafHkP8yG8DOTVoows0/edit?usp=docslist_api

**Comment by qiansen1386** [comment]
那么commiter 哪里可以看到呢？

**Comment by qiansen1386** [comment]
那么commiter 哪里可以看到呢？

**Comment by OlingCat** [comment]
呃....每个人的 commit 里就是自己啊 0.0
Cherry-Pick 的只是 Submitter 而已。

**Comment by qiansen1386** [comment]
并没有……

**Comment by OlingCat** [comment]
前面属于旧的没 merge，之后就会有了= =||
@minux 我们的 PR 转 CL 弄得咋样了？

**Comment by OlingCat** [comment]
@qiansen1386 我的锅= =||
现在重新设置Gerrit，对应文档也要重写，请耐心等候。
至于 Tour，我会先维护一份现有贡献者的名单，等部署到 Gerrit 上后就不用了。

**Comment by qiansen1386** [comment]
:joy: 感觉很麻烦的样子。最近忙着做很多乱七八糟的工作，没时间参与进来，实在抱歉。等我稳定下来会尽力来帮忙的。感谢老大的赏识
