### ISSUE TITLE
[简单描述一下要汇报的问题]

### ISSUE THREAD

**Issue by nicozhang** [Go-zh/tour#208]
上下文: https://tour.go-zh.org/moretypes/14

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码.

这个地方的翻译不准确：It should return a slice of length dy, each element of which is a slice of dx 8-bit unsigned integers。 

这个函数要返回一个长度是dy的slice， 且每个元素也是长度为dx的 8 位无符号整数slice。

**Comment by minux** [comment]
已经修正，谢谢汇报。
