### ISSUE TITLE
[编辑器消失]

### ISSUE THREAD

**Issue by orca-clock** [Go-zh/tour#212]
上下文: https://tour.go-zh.org/concurrency/7

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

![image](https://cloud.githubusercontent.com/assets/316126/11863648/749d0a8c-a4d0-11e5-84ff-4ed7f87257a4.png)

**Comment by OlingCat** [comment]
已记录，下次提交时解决。
（然而下次并不知道是什么时候。

**Comment by minux** [comment]
这个没问题，本来那页就没有编辑器：那页只是介绍
问题的第一部分，真正的习题在下一页。参见
https://tour.golang.org/concurrency/7
以及 golang/go#13048.
