### ISSUE TITLE
本机执行该实例错误

### ISSUE THREAD

**Issue by MillerRen** [Go-zh/tour#213]
上下文: https://tour.go-zh.org/moretypes/8

# command-line-arguments
./slices-of-slice.go:4: imported and not used: "fmt"
./slices-of-slice.go:5: imported and not used: "strings"
./slices-of-slice.go:21: undefined: printBoard

**Comment by minux** [comment]
你拷贝的源代码的时候没复制 printBoard 函数吧。

（也可能是你修改了编辑框里的代码，你可以点“重置为初始状态”
按钮恢复为原来的代码）

**Comment by MillerRen** [comment]
是的，谢谢：）
