### ISSUE TITLE
windows 无法按步骤离线安装

### ISSUE THREAD

**Issue by westwind027** [Go-zh/tour#215]
上下文: https://tour.go-zh.org/welcome/3

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

go get github.com/Go-zh/tour/gotour  完成后只有源码，不会自动编译。
进gotour目录编译后失败

**Comment by westwind027** [comment]
已解决！
解决方法：
1）go get github.com/golang/net/
2）在GOPATH路径下创建golang,org/x/目录
3）将github.com/golang里面的net拷贝到2）的目录
4）将github.com/Go-zh/tour/vendor/golang.org/x下的目录拷贝到2）的目录
5）进github.com/Go-zh/tour/gotour 重新运行go install

**Comment by minux** [comment]
你没开 GO15VENDOREXPERIMENT？
理论上直接

go get github.com/Go-zh/tour/gotour

就够了。

不过我突然意识到 vendor x/tour 的那几个包
似乎意义不大。playground 的 WebSocket
后端并不理会 Go-zh/tour/vendor 下的几个包……

另外，github.com/Go-zh/tools/playground/socket/socket.go
应该换成用 github.com/Go-zh/net/websocket.

**Comment by westwind027** [comment]
没开
