### ISSUE TITLE
字母“l”和数字“1”的区分不明确。

### ISSUE THREAD

**Issue by GitHanDong** [Go-zh/tour#216]
上下文: https://tour.go-zh.org/basics/8

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

**Comment by minux** [comment]
这就是 Inconsolata 字体的问题吧，多看看就能区分了。
英文版的 Go Tour 也是用这个字体。

**Comment by GitHanDong** [comment]
![qq 20160129135312](https://cloud.githubusercontent.com/assets/16949634/12668270/c4475070-c68f-11e5-8688-db3e311ef022.png)

_(:3 」∠)_
Q： 请用将文字中的“l”替换为"L"

**Comment by minux** [comment]
你浏览器的monospace字体是什么？

**Comment by OlingCat** [comment]
调整下自己的 monospace 等宽字体吧，推荐 Inconsolata-dz、Noto Mono 或 Menlo
