### ISSUE TITLE
当 i==0 时不会调用 f 函数， 这句话不对吧。

### ISSUE THREAD

**Issue by hongfeioo** [Go-zh/tour#217]
上下文: https://tour.go-zh.org/flowcontrol/10

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

func  main() {
      fmt.Println("When's Saturday?")
      v:=0
      switch  v{
      case  0:
           fmt.Println("00000")
      }
}

**Comment by minux** [comment]
那句话是针对这段代码说的：

switch i {
case 0:
case f():
}

如果 i == 0 那么第一个 case 就匹配了，因此不会调用 f() 函数啊。

http://play.golang.org/p/sJZm9NTPJM
