### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fhfuwei** [Go-zh/tour#218]
上下文: https://tour.go-zh.org/methods/9

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

Typo

`由于不支持复数，当 Sqrt 接收到一个负数时，应当返回一个非 nil 的错误值。`  把复数改成负数

**Comment by OlingCat** [comment]
突然发现老早就改了但一直还没 push = =||

**Comment by fhfuwei** [comment]
哈哈  找个时间push下，只有一个人维护吗？

**Comment by OlingCat** [comment]
目前只剩半个人了吧= =||

**Comment by qiansen1386** [comment]
:joy: 我还不会玩那个 code review 的东东。

**Comment by fhfuwei** [comment]
= =!

**Comment by OlingCat** [comment]
> Closed by #222
