### ISSUE TITLE
can't understand this two lines

### ISSUE THREAD

**Issue by Nicksxs** [Go-zh/tour#221]
上下文: https://tour.go-zh.org/methods/2

`type MyFloat float64`
float64 is a type, and MyFloat is same to float64?

`func (f MyFloat) Abs() float64 {`
here Abs() meas what, float64 is function's return type? func (f MyFloat) is the entry of the function?

**Comment by OlingCat** [comment]
1. MyFloat 是通过 float64 定义的类型，它们可以互相转换，但不是一个类型。 https://go-zh.org/ref/spec.old#类型声明
2. Abs() 是求绝对值，float64 是此方法（函数）的返回值，func (f MyFloat) 是方法的接收者，更多问题可查阅 https://go-zh.org/ref/spec.old#方法声明

> PS: 新版的 tour 换了更好的代码示例，然而咱还在拖坑中= =||

**Comment by Nicksxs** [comment]
原来学过一点C，`func (f MyFloat) Abs() float64 {`对这种表示不理解，函数不是包括参数跟返回类型就可以了么，`Abs()`是什么角色呢

**Comment by OlingCat** [comment]
Abs() 是方法名

**Comment by OlingCat** [comment]
方法名啊= =
