### ISSUE TITLE
在虚拟机中编译运行gotour后，点击运行总是报这个错：Program exited: fork/exec ./go: no such file or directory

### ISSUE THREAD

**Issue by wangfeiping** [Go-zh/tour#229]
是我Go的环境配置不对么？
root账户，在任意路径都可以执行go程序。
在源码中没找到具体在哪里执行go？
$>go env
GOARCH="amd64"
GOBIN="/apps/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/apps/gopath:/apps/go"
GORACE=""
GOROOT="/apps/go"
GOTOOLDIR="/apps/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by OlingCat** [comment]
go 的版本呢？1.6.2 表示无法复现....

**Comment by wangfeiping** [comment]
CentOS-6.6-x86_64-minimal.iso
go1.6.linux-amd64.tar.gz

可以正常编译运行，感觉应该不是Go的问题，不知道是不是因为我装的是 CentOS-6.6-x86_64-minimal 版本，所以有些依赖的软件没有安装。

尝试在任意路径下执行 exec 和 go 都可以执行。
gotour编译后也是在$GOROOT/bin路径下生成，和 go程序在同一目录下。
也是在$GOROOT/bin路径下运行，，可以format，其他功能都正常，但就是无法运行示例程序。

源码还没看明白，所以还没找到具体在哪里执行的，playground包里？

**Comment by minux** [comment]
Go 命令在 $PATH 里面吗？

**Comment by wangfeiping** [comment]
在，配置了$GOBIN，并添加到$PATH里了，在任意路径下可以执行go

**Comment by wangfeiping** [comment]
安装了go1.6.2.linux-amd64.tar.gz继续测试，也不行！
按照官方文档将go安装到 /usr/local 下，也不行！

在其他路径下（非$GOROOT/bin路径）执行 gotour，可执行，但是报下面的错：

    Program exited: exec: "go": executable file not found in $PATH

看来在$GOROOT/bin路径下执行gotour时go程序是可以找到的，否则报错信息应该一样。

看源码看到这一段：

     tour/gotour/local.go

    
    func init() {
	socket.Environ = environ
    }

    // environ returns the original execution environment with GOPATH
    // replaced (or added) with the value of the global var gopath.
    func environ() (env []string) {
	for _, v := range os.Environ() {
		if !strings.HasPrefix(v, "GOPATH=") {
			env = append(env, v)
		}
	}
	env = append(env, "GOPATH="+gopath)
	return
    }

这段应该与"Run"功能有关，突然怀疑是 $GOPATH 的问题(为了方便在$GOPATH中增加了$GOROOT):

    export GOPATH=/apps/gopath:$GOROOT

修改$GOPATH配置:

    export GOPATH=/apps/gopath

可以正常运行了！

**Comment by minux** [comment]
GOROOT 是不能加到 GOPATH 里面的。

$ GOPATH=$GOROOT go env
warning: GOPATH set to GOROOT ($GOROOT) has no effect

**Comment by OlingCat** [comment]
这问题算是用一个理论上没什么效果的方法解决了么= =？

**Comment by wangfeiping** [comment]
谢谢指点，一直这么用，没留意过竟然不能这么用，多谢多谢。

**Comment by qiansen1386** [comment]
@OlingCat  我看到有个Docker image https://hub.docker.com/r/shymega/gotour/builds/bwhtra4ryvewhdrbhhqpd7n/
不知道能不能用？

**Comment by minux** [comment]
Gotour 应该很高装吧，不至于为了它用个Docker container吧？

**Comment by qiansen1386** [comment]
O(∩_∩)O哈哈~，用 docker 不是更无脑么
