### ISSUE TITLE
moretypes 18 错误翻译

### ISSUE THREAD

**Issue by zgwldrc** [Go-zh/tour#230]
context: https://tour.go-zh.org/moretypes/18

refer to the chinese introduction part :
//map 的文法（续）
//如果顶级的类型只有类型名的话，可以在文法的元素中省略键名。

it means omit the key name  (it would be type name in fact)，this is conflict with the introduction within "https://tour.go-zh.org/moretypes/17"

**Comment by OlingCat** [comment]
新的翻译为 `若顶级类型只是一个类型名，你可以在文法的元素中省略它。`
@minux 我们的网站该更新了= =

**Comment by OlingCat** [comment]
Fixed by #225
