### ISSUE TITLE
无法访问导入的包"golang.org/x/tour/pic"

### ISSUE THREAD

**Issue by liqt91** [Go-zh/tour#242]
上下文: http://127.0.0.1:3999/moretypes/18

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

在本地教程的练习：切片一章中（ http://127.0.0.1:3999/moretypes/18 ），无法访问导入的包"golang.org/x/tour/pic"，使用 "go get golang.org/x/tour/pic" 也拉不下来，导致后续练习无法进行

**Comment by OlingCat** [comment]
墙的问题，之后会换服务器和导入路径来解决。
