### ISSUE TITLE
如何支持中文输出？

### ISSUE THREAD

**Issue by Hollywong** [Go-zh/tour#243]
上下文: https://tour.go-zh.org/welcome/1
在本地安装go后，不支持中文输出，不知道怎么解决？
编译结果如下：
-------------------------------
C:\Go\myworks>go run hello.go
# command-line-arguments
.\hello.go:6: invalid UTF-8 encoding

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

**Comment by Hollywong** [comment]
如何支持中文输出？

**Comment by minux** [comment]
你确定你的编辑器用的是 UTF-8 编码保存的源代码么？
没准是用 GBK 编码吧？

**Comment by OlingCat** [comment]
可以考虑使用 Sublime Text 或 Visual Studio Code 来写代码

**Comment by Hollywong** [comment]
几种编辑器都试了，建立文本文件，然后把文件后缀改成go，怎么改编码格式？

**Comment by Hollywong** [comment]
解决了在文本编辑里选择“文件”-“另存为”-“编码中”选择“UTF-8”即可，谢谢各位！
