### ISSUE TITLE
flowcontrol.article关于defer的描述

### ISSUE THREAD

**Issue by AlpherJang** [Go-zh/tour#249]
flowcontrol.article最底下关于defer的描述中有一句是推迟调用的函数其参数会立即求值，这句描述不是很清楚，其参数立即求值是什么意思呢

**Comment by OlingCat** [comment]
设
```
...
i := 2
defer f(i+3)
...
```
那么在执行到 `defer f(i+2)` 这里时，`f` 的参数会先求值为 `5`，即把 `defer f(5)` 压栈，等到外层函数返回，`f(5)` 才执行。
