### ISSUE TITLE
网页沙盘运行的结果和我本地运行的结果不一样

### ISSUE THREAD

**Issue by f839903061** [Go-zh/tour#255]
上下文: # **_https://tour.go-zh.org/moretypes/12_**

正在学习go  append函数，示例代码如下：
package main

import "fmt"

func main() {
	var a []int
	printSlice("a", a)

	// append works on nil slices.
	a = append(a, 0)
	printSlice("a", a)

	// the slice grows as needed.
	a = append(a, 1)
	printSlice("a", a)

	// we can add more than one element at a time.
	a = append(a, 2, 3, 4)
	printSlice("a", a)
}

func printSlice(s string, x []int) {
	fmt.Printf("%s len=%d cap=%d %v\n",
		s, len(x), cap(x), x)
}

网页沙盘运行结果（你也可以直接点击网页沙盘里的运行按钮）：
a len=0 cap=0 []
a len=1 cap=2 [0]
a len=2 cap=2 [0 1]
a len=5 cap=8 [0 1 2 3 4]      留意cap

而我使用sublime text编辑器的运行结果（源代码代码我是直接拷贝过来的）：
a len=0 cap=0 []
a len=1 cap=1 [0]
a len=2 cap=2 [0 1]
a len=5 cap=6 [0 1 2 3 4]      留意cap

最后得出的cap一个是8一个是6居然不一样！

**Comment by OlingCat** [comment]
见 #261 ，Go 只保证新分配的空间（即底层数组）能够容纳当前元素，不保证容量，用完了会再分配。
