### ISSUE TITLE
第三行文字错误

### ISSUE THREAD

**Issue by tashuo** [Go-zh/tour#257]
上下文: https://tour.go-zh.org/methods/9

“由于不支持复数” 应该是 "由于不支持负数"

**Comment by SnowOnion** [comment]
这不是一个错误。@mikespook
原文：Sqrt should return a non-nil error value when given a negative number, as it doesn't support complex numbers. https://tour.golang.org/methods/20
负数放到 `sqrt` 里产生了复数，很奇妙。

但是原翻译也不太好，“不支持复数”的主语是谁？
建议翻译：“由于 `Sqrt` 没有支持返回复数”。

**Comment by OlingCat** [comment]
呃..发现原来就改掉了，现在部署在 go-zh.org 上的还是旧版= =||
