### ISSUE TITLE
网页打不开了

### ISSUE THREAD

**Issue by LeventZheng** [Go-zh/tour#258]
上下文: https://tour.go-zh.org/welcome/1

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码
script.js:544 GET https://tour.go-zh.org/lesson/ net::ERR_SPDY_PING_FAILED
script.js:507 error loading lessons :  Object {data: "", status: 0, config: Object, headers: function}

**Comment by OlingCat** [comment]
目前的方案只能是 Chrome+梯子，咱回头换服务器试一下= =

**Comment by OlingCat** [comment]
close #251
