### ISSUE TITLE
struct literal 应翻译成 “结构体字面量/字面值” 而非现在的 “结构体文法”

### ISSUE THREAD

**Issue by SnowOnion** [Go-zh/tour#259]
上下文: https://tour.go-zh.org/moretypes/5

struct literal 应翻译成 “结构体字面量/字面值” 而非现在的 “结构体文法”。
其他语言中对 literal 一般如此翻译。

**Comment by SnowOnion** [comment]
同样地，
切片文法 应为 切片字面量 https://tour.go-zh.org/moretypes/9
映射的文法 应为 映射字面量 https://tour.go-zh.org/moretypes/20 https://tour.go-zh.org/moretypes/21

**Comment by mikespook** [comment]
如果没记错，“文法”这个翻译是我最初引入 gotour 的。
没有使用“字面量/字面值” 的原因是感觉 literal 既不是“量”也不是“值”（虽然大部分翻译如此命名，但是感觉还是十分混淆）。

从另一个角度来说，“文法”的翻译也不够好，也看到过“文法符号”的翻译。不过如果简称“文符”似乎又有些诡异了。

**Comment by SnowOnion** [comment]
@mikespook 
>  既不是“量”也不是“值”

well，这**是**个问题。

说 “文法” 我会想到 形式文法、production rule 那一套。

**Comment by mikespook** [comment]
是的，“文法”也不是十分妥当。
有时我甚至想用“语素”或者“语素符号”来翻译，但是感觉理解起来更加晦涩。

我最近一两年没空再做大量翻译了，所以提供一些信息在这里，仅供参考。
个人并不反对在这里将其翻译为“字面量”，如果大家理解起来觉得没有问题的话。

**Comment by SnowOnion** [comment]
@mikespook 
感谢。辛苦开路者了：）

有没有好的途径搞个投票之类的，征求 Golang 中文用户们的意见呢？
如果没有，我去改成“字面量”、提 PR、以观后效？

**Comment by OlingCat** [comment]
@SnowOnion GoSpec 的翻译里直接用了「字面」，因为它连「量」都不算= =

**Comment by SnowOnion** [comment]
@OlingCat = =、更不像名词了
GoSpec 指的是 https://golang.org/ref/spec 还是 https://github.com/orfjackal/gospec ？
中文翻译的项目在哪里呀？

**Comment by OlingCat** [comment]
@SnowOnion https://go-zh.org/ref/spec.old
源码就在这里啊，乃有兴趣加入么0.0？
