### ISSUE TITLE
一个空切片append一个元素cap应该是1

### ISSUE THREAD

**Issue by anyeshe** [Go-zh/tour#261]
上下文: https://tour.go-zh.org/moretypes/12

a len=0 cap=0 []
a len=1 cap=2 [0]   这个地方cap应该是1
a len=2 cap=2 [0 1]
a len=5 cap=8 [0 1 2 3 4]

**Comment by OlingCat** [comment]
没问题，底层数组在 append 后重新分配了，但分配的容量不保证大小，只保证能容纳当前元素就行，如果 append 超容量了就再分配一块。
