### ISSUE TITLE
[简单描述一下要汇报的问题]

### ISSUE THREAD

**Issue by pekita1** [Go-zh/tour#263]
上下文: https://tour.go-zh.org/flowcontrol/10

today := time.Now()
fmt.Println(today)
为什么我这里的输出一直为2009-11-10 23:00:00 UTC这个起点时间呢？当前真正的时间一直得不到

**Comment by mikespook** [comment]
See https://blog.golang.org/playground

> Although all these things are supported today, the first version of the playground, launched in 2010, had none of them. The current time was fixed at 10 November 2009, time.Sleep had no effect, and most functions of the os and net packages were stubbed out to return an EINVALID error.

**Comment by pekita1** [comment]
Thanks! I read the blog before and I also have the question. What I used looks not like the first version of the playground. In this link (https://tour.golang.org/welcome/4), it says that "the time begins at 2009-11-10 23:00:00 UTC ", not fixed.
