### ISSUE TITLE
[翻译笔误]

### ISSUE THREAD

**Issue by current1990** [Go-zh/tour#269]
上下文: https://tour.go-zh.org/methods/9

方法和接口一节，第九页

由于不支持**复数**，当 Sqrt 接收到一个负数时，应当返回一个非 nil 的错误值。

应该为
由于不支持**负数**，当 Sqrt 接收到一个负数时，应当返回一个非 nil 的错误值。

**Comment by OlingCat** [comment]
​这里没错，因为对负数开平方根会返回复数。​

2017-11-05 22:56 GMT+08:00 current1990 <notifications@github.com>:

**Comment by current1990** [comment]
这样似乎读起来有一些奇怪，这句话读起来第一反应通常是

Sqrt不能接受*负数*作为参数，而不是Sqrt无法处理*负数*并返回*复数*

不过这个解释也能说得通就是了

**Comment by OlingCat** [comment]
感谢建议。源码已更新，稍后会重新部署。

2017-11-06 10:54 GMT+08:00 current1990 <notifications@github.com>:

**Comment by OlingCat** [comment]
网站翻译已更新，欢迎提出意见和建议。
