### ISSUE TITLE
[map的创建是可以通过make，但是不是必须啊]

### ISSUE THREAD

**Issue by ThomasHuke** [Go-zh/tour#272]
上下文: https://tour.go-zh.org/moretypes/16

详细的内容：
首先make是可以创建map这个当然是肯定的，但是没有make也可以定义一个map

A map maps keys to values.
The zero value of a map is nil. A nil map has no keys, nor can keys be added.
The make function returns a map of the given type, initialized and ready for use.

原文的意思是 “可以” 使用make进行初始化，并没有表达出一定要使用make的意思，希望你们可以改为“可以使用make进行初始化”这种表达方式。

**Comment by OlingCat** [comment]
因为是旧版的缘故，源码中已更新。

**Comment by OlingCat** [comment]
网站翻译已更新，欢迎提出意见和建议。
