### ISSUE TITLE
rand.Intn(10) 返回的总是1 

### ISSUE THREAD

**Issue by nicozhang** [Go-zh/tour#273]
上下文: https://tour.go-zh.org/basics/1

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

例子中 rand.Intn(10) 总是返回1，这个方法应该是随机吧

**Comment by OlingCat** [comment]
因为是伪随机数的缘故，种子一样，第一次生成的一定一样。想要不同的话调用 Seed 初始化好 Source 后每次调用 s.New() 就能获得不同的随机数。
