### ISSUE TITLE
go get github.com/Go-zh/tour/gotour

### ISSUE THREAD

**Issue by kingdombuilding** [Go-zh/tour#275]
➜  Desktop go get github.com/Go-zh/tour/gotour
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by linanwx** [comment]
我也是
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by linanwx** [comment]
@OlingCat

**Comment by OlingCat** [comment]
已修复，请通过 `go get -u github.com/Go-zh/tour/gotour` 命令重试。
