### ISSUE TITLE
中文翻译有误

### ISSUE THREAD

**Issue by kaitaow** [Go-zh/tour#276]
上下文: https://tour.go-zh.org/basics/13

“与 C 不同的是 Go 的在不同类型之间的项目赋值时需要显式转换。”
应该是
“与 C 不同的是 Go 在不同类型之间相互赋值时需要显式转换。”

上下文: https://tour.go-zh.org/flowcontrol/4
"如果省略了循环条件，循环就不会结束，因此可以用更简洁地形式表达死循环。"
应该是
"如果省略了循环条件，循环就不会结束，因此可以用更简洁的形式表达死循环。"

**Comment by OlingCat** [comment]
网站上的翻译已过期，请参考源码中的翻译。

**Comment by OlingCat** [comment]
网站翻译已更新，欢迎提出意见和建议。
