### ISSUE TITLE
append的返回值和本地运行不符

### ISSUE THREAD

**Issue by IsaacMu** [Go-zh/tour#277]
上下文: https://tour.go-zh.org/moretypes/12

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码
在tour里，func main() {
	var a []int
	printSlice("a", a)

	// append works on nil slices.
	a = append(a, 0)
	printSlice("a", a)

	// the slice grows as needed.
	a = append(a, 1)
	printSlice("a", a)

	// we can add more than one element at a time.
	a = append(a, 2, 3, 4)
	printSlice("a", a)
}

func printSlice(s string, x []int) {
	fmt.Printf("%s len=%d cap=%d %v\n",
		s, len(x), cap(x), x)
}
结果 最后a的cap显示是8，但是在自己本地下载的go，cap返回是6

**Comment by OlingCat** [comment]
编译器会视情况自动分配 cap，见Go语言规范。
