### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by carlosqin9068** [Go-zh/tour#279]
package golang.org/x/tools/imports: unrecognized import path "golang.org/x/tools/imports" (https fetch: Get https://golang.org/x/tools/imports?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
@OlingCat

**Comment by OlingCat** [comment]
已修复，请用 `go get -u` 重试
