### ISSUE TITLE
个人觉得 等价二叉树 改成 等价二叉搜索树 会好点

### ISSUE THREAD

**Issue by muzea** [Go-zh/tour#280]
上下文: https://tour.go-zh.org/concurrency/8

原版教程里面有提到，这个地方是排序过的（中文这边没有翻译这个注释），其实是指这个地方是二叉搜索树。
开始的时候一直在想怎么排序的问题，可以说是非常尴尬了：（

**Comment by OlingCat** [comment]
感谢建议！网站上部署的尚未更新，请参阅最新的翻译。
