### ISSUE TITLE
"切面"修改成"切片"

### ISSUE THREAD

**Issue by charliex2** [Go-zh/tour#281]
上下文: https://tour.go-zh.org/moretypes/13

原文"_切面可以用内建函数 make 来创建，这也是你创建动态数组的方式。_"中的"**切面**"是否应该改成 "**切片**"?

**Comment by OlingCat** [comment]
是的，错别字= =||
感谢指正~！

**Comment by lingfengchencn** [comment]
http://tour.go-zh.org  上面没更新哦？

**Comment by OlingCat** [comment]
呃.. tour.go-zh.org 上并不会随时更新的= =
