### ISSUE TITLE
运行的示例代码中的导入路径错误

### ISSUE THREAD

**Issue by lucas1993ch** [Go-zh/tour#292]
上下文: https://tour.go-zh.org/methods/22

package main

import "github.com/Go-zh/tour/reader"

type MyReader struct{}

// TODO: Add a Read([]byte) (int, error) method to MyReader.

func (r MyReader) Read(b []byte) (int, error) {
	b[0] = "A"
	return 1, nil
}

func main() {
	reader.Validate(MyReader{})
}

prog.go:3:8: cannot find package "github.com/Go-zh/tour/reader" in any of:
	/usr/local/go/src/github.com/Go-zh/tour/reader (from $GOROOT)
	/go/src/github.com/Go-zh/tour/reader (from $GOPATH)

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

**Comment by OlingCat** [comment]
和 #290 原因相同，是无脑替换导入路径导致的= =||
