### ISSUE TITLE
appengine 版本有一处语句不通顺

### ISSUE THREAD

**Issue by pityonline** [Go-zh/tour#299]
上下文：https://tour.go-zh.org/concurrency/11

appengine 版本显示为：
> 一旦安装了 Go， 应当继续阅读的内容。

https://github.com/Go-zh/tour/blob/59e9051b837f2fe4a6eb91e9f8c36d2d0b337e94/content/concurrency.article#L174

此处的代码未在 appengine 上显示出来，我没有 appengine 环境，不知道在本地怎么调试 appengine 版本的显示，请排查。

**Comment by OlingCat** [comment]
因为 go-zh.org 并不是 GAE = =||

**Comment by pityonline** [comment]
那是否有方法改进它在 go-zh.org 上的显示？或者是否有在本地调试的方法？

**Comment by OlingCat** [comment]
乃可以尝试自己在本地开个 GAE 然后部署，或者 GAE 也有免费版=w=

**Comment by pityonline** [comment]
想起来我其实有 GAE，多年没用了，抽空我调试下看看。
