### ISSUE TITLE
https://tour.go-zh.org/moretypes/23 练习问题

### ISSUE THREAD

**Issue by woodliu** [Go-zh/tour#301]
上下文: https://tour.go-zh.org/moretypes/23

FAIL
 f("The quick brown fox jumped over the lazy dog.") =
  map[string]int{"brown":1, "jumped":1, "over":1, "dog":1, "The":1, "quick":1, "lazy":1, "fox":1, "the":1}
 want:
  map[string]int{"over":1, "lazy":1, "dog.":1, "The":1, "quick":1, "brown":1, "fox":1, "jumped":1, "the":1}

check the standard answer  "dog.":1 ,"dog."shoudn't treat as a word

**Comment by OlingCat** [comment]
这个练习需要你事先处理好标点符号 .

**Comment by minvedacat** [comment]
原英语教程里提示用string.Fields，首先因为是英文教程，标点符号的情况当然可以作为拓展，我还喜欢用emoji怎么办呢。
另外看文档就知道它只认出了字母就是空格的string，就在这个方法的下面有这个[string.FieldsFunc](https://golang.org/src/strings/strings.go?s=9429:9482#L363)可以指定处理Fields的具体Func f，也有参考代码。虽然可能会因为这个f导致crash，但是即使对中文的标点符号也能处理好。

**Comment by minvedacat** [comment]
的确原版教程的‘word’ 联系答案也带了标点符号，说明是使用strings.Fields的结果
>FAIL
 f("I am learning Go!") =
  map[string]int{"I":1, "am":1, "learning":1, "Go":1}
 want:
  map[string]int{"Go!":1, "I":1, "am":1, "learning":1}
