### ISSUE TITLE
bad websocket origin

### ISSUE THREAD

**Issue by datafeng** [Go-zh/tour#303]
bad websocket origin

**Comment by OlingCat** [comment]
详细情况？

**Comment by fhq** [comment]
linux下面用 -http 0.0.0.0:3999运行，在其它机器访问过来，页面打开没有问题。但那个websocket好像就不行。就是点运行的时候一直在等待~~

**Comment by mikespook** [comment]
Check here for the further details: https://aleph0.me/2016/01/run-offical-go-language-tutorial-a-tour-of-go-on-a-server/

And I don't think we should fix this directly. The people who want to run a gotour and publish the service should modify the source code by themselves and take their own risk.
