### ISSUE TITLE
文本中代码少了个冒号

### ISSUE THREAD

**Issue by immct** [Go-zh/tour#305]
上下文: https://tour.go-zh.org/moretypes/1

指针
Go 拥有指针。指针保存了值的内存地址。

类型 *T 是指向 T 类型值的指针。其零值为 nil。

var p *int
& 操作符会生成一个指向其操作数的指针。

i := 42
p = &i    // **这里应该是 `p:= &i` 吧**

**Comment by OlingCat** [comment]
没问题，:= 表示声明并定义，前面已经声明了 p，这里直接赋值就好了。
