### ISSUE TITLE
页面go代码无法运行 https://tour.go-zh.org/moretypes/13

### ISSUE THREAD

**Issue by Antknt47** [Go-zh/tour#306]
上下文: https://tour.go-zh.org/moretypes/13

在这个页面上使用默认代码点击运行，输出框无内容，console提示:
    "Uncaught TypeError: Cannot read property 'length' of null"

点击终止，console提示
    "Error: $apply already in progress"

任意修改代码，如在打印内容中增加一个字符或者在换行处加入空格后，点击运行上述问题消失，输出正常。

刷新后问题仍存在。

环境：win10, chrome 62.0.3202.89

**Comment by OlingCat** [comment]
经个人测试无法重现此问题，考虑清空缓存或换其它浏览器重试。

**Comment by Antknt47** [comment]
我也复现不出来了 估计是当时的缓存的锅
