### ISSUE TITLE
代码出现语法错误而无法运行

### ISSUE THREAD

**Issue by mzz2017** [Go-zh/tour#307]
上下文: https://tour.go-zh.org/moretypes/10

```go
package main

import "fmt"

func main() {
	s := [6]int{2, 3, 5, 7, 11, 13}

	s = s[1:4]//这里无法将一个切片赋值给一个数组变量
	fmt.Println(s)

	s = s[:2]
	fmt.Println(s)

	s = s[1:]
	fmt.Println(s)
}

```

**Comment by OlingCat** [comment]
数组长度是数组类型的一部分，且数组是不可变的数据类型，而下面的切片明显与数组的类型不符。左侧的`var a [10]int` 只是示意了数组长度与创建切片的关系，如果要对切片重新赋值，请指定别的变量名。
详情请参考 Go 语言规范中关于切片和底层数组的部分。

**Comment by OlingCat** [comment]
@mzz2017 第六行的方括号内并没有6，如果你修改了源代码，请点击右下方的“重置”按钮再查看源代码。

**Comment by mzz2017** [comment]
抱歉，是我的问题。打扰了。
