### ISSUE TITLE
直接运行示例代码得到如下错误提示

### ISSUE THREAD

**Issue by jjling2011** [Go-zh/tour#308]
上下文: https://tour.go-zh.org/concurrency/4

错误提示：
> /usr/local/go/src/sync/pool.go:9:2: read /usr/local/go/src/runtime/symtab_test.go: read /usr/local/go/src/runtime/symtab_test.go: cannot allocate memory

代码中任意位置加个空行就可以正常运行。
是的，你没看错！加个空行就不报错！

**Comment by OlingCat** [comment]
现在好像没啥问题了....

**Comment by jjling2011** [comment]
恩,看来是修复了.
issue closed.
