### ISSUE TITLE
在线编译后结果不对

### ISSUE THREAD

**Issue by zzz45683** [Go-zh/tour#313]
上下文: https://tour.go-zh.org/basics/16

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

func main() {
	var test1 = 1 << 29
	var test2 = 1 << 29
	
	fmt.Println(test1)	
	fmt.Println(test2)
	
	fmt.Printf("test1 is of type %T\n", test1)
	fmt.Printf("test2 is of type %T\n", test2)
	
	test1 = test1 * 2
	test2 = test2 * 10
	
	fmt.Println(test1)
	fmt.Println(test2)
}

536870912
536870912
test1 is of type int
test2 is of type int
1073741824
1073741824

**Comment by OlingCat** [comment]
因为溢出了。

**Comment by zzz45683** [comment]
呃。。。
因为本地go试过，能得到正常结果
536870912
536870912
test1 is of type int
test2 is of type int
1073741824
5368709120

**Comment by OlingCat** [comment]
诡异....

zzz45683 <notifications@github.com> 于 2018年8月10日周五 17:12写道：
