### ISSUE TITLE
对“Literal"的翻译问题

### ISSUE THREAD

**Issue by Monsooooon** [Go-zh/tour#322]
上下文: https://tour.go-zh.org/moretypes/9

Literal 翻译成 “字面量” 而不是 “文法” 可能会更好一点。

**Comment by mikespook** [comment]
印象中对这个翻译好像有过讨论。
由于这个词里面的“量”，我觉得“字面量”这个翻译是不恰当且具有误导性的。
不过，按照惯例这里确实是应该用字面量，以便对应其他语言和文档中的翻译。
Dilemma
