### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by jichangee** [Go-zh/tour#328]
https://tour.go-zh.org/basics/7

计算结果：x = 7.555555556
                  y = 9.444444444
输出的结果却是x = 7, y = 10

为什么x向下取整，而y向上取整？

**Comment by mikespook** [comment]
y 是由整數 17 - 7 得到的結果。這是因爲 x 是一個 int 型整數，所以在進行乘除運算的時候，已經將其取整爲 7。所以 y 的計算實際上是整數 17 - 7。

如果中間過程使用 float64 進行計算，就會得到不同的結果：https://play.golang.org/p/qCPHv9luh19

**Comment by jichangee** [comment]
明白了，万分感谢～
