### ISSUE TITLE
希望说明文档有所改进

### ISSUE THREAD

**Issue by fadelover** [Go-zh/tour#331]

**Comment by fadelover** [comment]
这个项目怎么了？提供的在线网站无法访问，本地部署教程不知所云，强烈质疑中文文档水平

**Comment by fadelover** [comment]
Go 语言官方教程中文版 http://tour.go-zh.org 无法访问
本地部署教程不全

**Comment by dotDuck** [comment]
- 因为目前在线版无法访问，按照离线安装说明，安装完后运行gotour，只显示`github.com/Go-zh/tour/gotour has moved to golang.org/x/tour`，没有浏览器访问的链接说明；
- 无法找到本地运行tour服务器脚本**dev_appserver.py **
- 相关文档说明确实需要完善一下

**Comment by fadelover** [comment]
> * 因为目前在线版无法访问，按照离线安装说明，安装完后运行gotour，只显示`github.com/Go-zh/tour/gotour has moved to golang.org/x/tour`，没有浏览器访问的链接说明；
> * 无法找到本地运行tour服务器脚本 **dev_appserver.py**
> * 相关文档说明确实需要完善一下

找了半天，发现迁移到这了 http://go-tour-zh.appspot.com/welcome/1
然而代码无法运行
大概看了全部的内容，觉得要么看官方英文教程，要么还是自己看书吧。。。

**Comment by OlingCat** [comment]
安装完成后直接执行 `tour` 就可以了。tour.go-zh.org 用的是 @minux 的VPS，出现了啥状况咱也不知道= =

**Comment by OlingCat** [comment]
PS：如果有人愿意接手维护的话可以找咱加入项目组。

**Comment by OlingCat** [comment]
> * 因为目前在线版无法访问，按照离线安装说明，安装完后运行gotour，只显示`github.com/Go-zh/tour/gotour has moved to golang.org/x/tour`，没有浏览器访问的链接说明；
> * 无法找到本地运行tour服务器脚本 **dev_appserver.py**
> * 相关文档说明确实需要完善一下

最新的 GAE 部署方式变了，可参考 [Go App Engine 官方文档](https://cloud.google.com/appengine/docs/standard/go111/runtime)。 README 已更新。
