### ISSUE TITLE
[简单描述一下要汇报的问题]

### ISSUE THREAD

**Issue by yangyangnote** [Go-zh/tour#333]
上下文: https://tour.go-zh.org/flowcontrol/7

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

func pow(x, n, lim float64) float64 {
	if v := math.Pow(x, n); v < lim {
		return v
	} else {
		fmt.Printf("%g >= %g\n", v, lim)
	}
	return lim
}

func main() {
	fmt.Println(
		pow(3, 2, 10),
		pow(3, 3, 20),
	)
}

The answer should be 
9, 27 >= 20

Instead of
27 >= 20
9 20

Or is there a problem with my understanding?

**Comment by OlingCat** [comment]
你搞混了打印输出和求值结果的区别。
`pow(3, 2, 10)` 的求值结果为 9，而 `pow(3, 2, 10)` 的求值结果为 20，只不过它在求值过程中由于带有副作用，所以先打印输出了 27 >= 20。二者求值完毕后，main 中才把 9 和 27 打印了出来。

**Comment by yangyangnote** [comment]
1."pow(3, 2, 10) 的求值结果为 9，而 pow(3, 2, 10) 的求值结果为 20" 是不是理解为
pow(3, 2, 10) 的求值结果为 9，而 pow(3, 3, 20) 的求值结果为 20

2.应该是我理解程序的执行顺序弄错了,先执行pow(3, 3, 20)else判断的输出,在执行最外面fmt.Println对求值的输出

谢谢 @OlingCat
