### ISSUE TITLE
cannot find package "github.com/Go-zh/tour/pic"

### ISSUE THREAD

**Issue by luaxlou** [Go-zh/tour#334]
上下文: https://tour.go-zh.org/methods/25

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

prog.go:3:8: cannot find package "github.com/Go-zh/tour/pic" in any of:
	/usr/local/go/src/github.com/Go-zh/tour/pic (from $GOROOT)
	/go/src/github.com/Go-zh/tour/pic (from $GOPATH)

**Comment by plus875** [comment]
同遇到这个问题

**Comment by cjmmya** [comment]
https://tour.go-zh.org/moretypes/18
这个问题运行时，同样遇到了这个问题
prog.go:3:8: cannot find package "github.com/Go-zh/tour/pic" in any of:
	/usr/local/go/src/github.com/Go-zh/tour/pic (from $GOROOT)
	/go/src/github.com/Go-zh/tour/pic (from $GOPATH)

**Comment by symoo** [comment]
可以暂且使用英文官网的链接代替 `import "golang.org/x/tour/pic"`
