### ISSUE TITLE
tour.go-zh.org_moretypes_18  github.com/Go-zh/tour/pic 包丢失

### ISSUE THREAD

**Issue by AndyBoat** [Go-zh/tour#336]
上下文: https://tour.go-zh.org/moretypes/18
尝试run时得到如下返回:
prog.go:3:8: cannot find package "github.com/Go-zh/tour/pic" in any of:
	/usr/local/go/src/github.com/Go-zh/tour/pic (from $GOROOT)
	/go/src/github.com/Go-zh/tour/pic (from $GOPATH)

**Comment by OlingCat** [comment]
Same as #334
