### ISSUE TITLE
https://tour.go-zh.org/moretypes/23（练习：映射）中示例代码过期

### ISSUE THREAD

**Issue by Laurence-042** [Go-zh/tour#339]
上下文: https://tour.go-zh.org/moretypes/23

试图运行初始代码会产生如下错误信息：
prog.go:4:2: cannot find package "github.com/Go-zh/tour/wc" in any of:
	/usr/local/go/src/github.com/Go-zh/tour/wc (from $GOROOT)
	/go/src/github.com/Go-zh/tour/wc (from $GOPATH)

可以将import中的"github.com/Go-zh/tour/wc"改为"golang.org/x/tour/wc"

**Comment by AJenpan** [comment]
哈哈,我也发现了,刚刚想来报告,结果发现你先了..
一起学GOLANG呀
https://tour.go-zh.org/moretypes/23
