### ISSUE TITLE
"切片的长度与容量"中翻译的小问题

### ISSUE THREAD

**Issue by cdfmlr** [Go-zh/tour#346]
上下文: https://tour.go-zh.org/moretypes/11

这一页里说明的最后一段：

> 你可以通过重新切片来扩展一个切片，给它提供足够的容量。试着修改示例程序中的切片操作，向外扩展它的容量，看看会发生什么。

这一段给人感觉表述不是很清晰，并且翻译似乎有误😂

对应的[原文](https://tour.golang.org/moretypes/11)是：

> You can extend a slice's length by re-slicing it, provided it has sufficient capacity. Try changing one of the slice operations in the example program to extend it beyond its capacity and see what happens.

我认为英文原文表达的意思是：

"只要具有足够的容量，你便可以通过重新切片来拓展一个切片。试着修改示例程序中的某个切片操作，使其长度超过容量（或者说将其扩展到超出其容量范围），看看会发生什么。"

**Comment by OlingCat** [comment]
是的，感谢指正！
