### ISSUE TITLE
缺少具体说明

### ISSUE THREAD

**Issue by BlameKidd** [Go-zh/tour#347]
上下文: https://tour.go-zh.org/basics/8

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

package main

import "fmt"

var c, python, java bool

func main() {
	var i int
	fmt.Println(i, c, python, java)
}

没有具体说明为什么没有赋值的变量i，打印出来是0，对新手来说有些不太友好

**Comment by BlameKidd** [comment]
虽然在后面提到了。

**Comment by OlingCat** [comment]
唔..咱是觉得后面会看到的就在这里先留个疑问吧= =
