### ISSUE TITLE
本 Issue 是绝佳的反面例子，挂在这里供后人参考。

### ISSUE THREAD

**Issue by liangazhou** [Go-zh/tour#348]
上下文: https://tour.go-zh.org/flowcontrol/8

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

**Comment by OlingCat** [comment]
1. 标题都没改，留着个 [简单描述一下要汇报的问题]，谁知到你遇到了啥问题= =？
2. 你只给了上下文连接，别的啥都没有，咱还得点开页面跳过去，看看是到底是个啥= =||
3. 最后一句话是给你看的，不是给我看的，无关信息请删除= =||
4. 咱勉为其难地跳过去了，发现是个练习，于是聪明如咱猜到你肯定是运行报错了。然而这段代码不完整是要交给你自己去完成的，点运行当然会报错。但凡你稍微懂点英语或哪怕用工具翻译一下错误也能看明白。
5. 本喵很生气，后果很严重，咱要把这个 Issue 挂出来以警示后人= =||

**Comment by maoxuner** [comment]
也许这个人要讲的跟我的是同一个问题吧 #364

**Comment by strawbreey** [comment]
这个应该是手误，点击`https://tour.go-zh.org/flowcontrol/8`页面上右上角debug的按钮，而内容没做校验并自动提交了issue

**Comment by OlingCat** [comment]
> 这个应该是手误，点击`https://tour.go-zh.org/flowcontrol/8`页面上右上角debug的按钮，而内容没做校验并自动提交了issue

可问题是为啥手误也会去点一下提交啊= =

**Comment by DengYuncheng27** [comment]
虽然挂在这里了，但是看issue里面还是有好多一样的，哈哈。
