### ISSUE TITLE
觉得有个描述有点拗口

### ISSUE THREAD

**Issue by flamefox** [Go-zh/tour#349]
上下文: https://tour.go-zh.org/concurrency/4

```之后 ok 会被设置为 false。```
这句话在源码之后，前后有个很大的阅读中断，给人的感觉是在执行完语句后，当前值会在之后被其他的内容改变

个人觉得应该改成
```之后 ok 的值```**将**```会是 false。```
或者调整下语序，将其他描述的内容放到这一行也可以？

**Comment by OlingCat** [comment]
嗯，确实，之后会再打磨下语句。
