### ISSUE TITLE
[简单描述一下要汇报的问题]

### ISSUE THREAD

**Issue by yussuy** [Go-zh/tour#350]
上下文: https://tour.go-zh.org/basics/16

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

**Comment by OlingCat** [comment]
不是..你们都看不懂中文的么= =？

**Comment by yussuy** [comment]
抱歉，应该是误点了链接右上角的debug跳过来，然后不小心提交了，您没回复前自己都没注意到，实在不好意思。（弱弱说一句，package golang.org/x/net/websocket: exit status 128 是readme提到的依赖库的导入路径挂了的问题吗）

**Comment by OlingCat** [comment]
抱歉，之前说话有点冲，可能之前也有人是这么误触的，需要改下 debug。

后面这个问题是因为官方启用了 go mod 的缘故，如果直接把官方库转到 GitHub 上是没办法解决依赖问题的，总会有一个版本的库会依赖到
golang.org/x 上，而且 GitHub 在国内的流量已经劣化到不翻墙没法下载完整依赖库了，所以建议直接挂梯子然后用 go get 获取
tour。

Shuo Yu <notifications@github.com> 于 2019年4月30日周二 01:35写道：
