### ISSUE TITLE
The tour website cannot be accessed normally

### ISSUE THREAD

**Issue by AJenpan** [Go-zh/tour#351]
不能正常访问网站,chrome 提示如下:
攻击者可能会试图从 tour.go-zh.org 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_DATE_INVALID
 
您可以选择向 Google 发送一些系统信息和网页内容，以帮助我们改进安全浏览功能。隐私权政策
tour.go-zh.org 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 tour.go-zh.org 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 tour.go-zh.org，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 tour.go-zh.org，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by OlingCat** [comment]
OK 了。
