### ISSUE TITLE
中文语言界面没有英语的链接

### ISSUE THREAD

**Issue by xcjiang** [Go-zh/tour#354]
上下文: https://tour.go-zh.org/welcome/2

在上面的页面里，有各种语言的链接，唯独没有英语。

**Comment by OlingCat** [comment]
啊..因为是直接翻译的英文，忘加了，稍后会补上。

**Comment by OlingCat** [comment]
Fixed by https://github.com/Go-zh/tour/commit/6d909196b60b6f5905d8e06cd1cfc3bcf7297070
