### ISSUE TITLE
Go指南 离线版教程命令行命令的歧义 并且package又挂了......

### ISSUE THREAD

**Issue by ZZZenglihan** [Go-zh/tour#356]
https://tour.go-zh.org/welcome/3
命令行里的命令是这样的
get -u github.com/Go-zh/tour tour
是不是把最后面的tour去掉比较好，刚开始我真以为后面有个tour......

package我这里显示package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket" (https fetch: Get https://golang.org/x/net/websocket?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by ZZZenglihan** [comment]
@OlingCat

**Comment by Ming-Lei** [comment]
进入$GOPATH/src/golang.org/x目录
从镜像仓库clone [net包](https://github.com/golang/net)
重新安装离线教程

**Comment by OlingCat** [comment]
啊，后面那个 tour 应该是第二行，表示执行= =
以及..安装请自备梯子= =
Fixed by https://github.com/Go-zh/tour/commit/6d909196b60b6f5905d8e06cd1cfc3bcf7297070

**Comment by zieglar** [comment]
https://tour.go-zh.org/welcome/3
这个页面显示的 第二个 tour 依然没有换行
