### ISSUE TITLE
Reader 例子答案疑问

### ISSUE THREAD

**Issue by yangyangnote** [Go-zh/tour#358]
上下文
https://tour.go-zh.org/methods/21

教程中说io 包指定了 io.Reader 接口，它表示从数据流的末尾进行读取.但是从例子的打印结果来看 r.Read(b) r在调用Read方法时 是从Hello, Reader! 数据流的开始进行读取的？我理解错了吗？

```
n = 8 err = <nil> b = [72 101 108 108 111 44 32 82]
b[:n] = "Hello, R"
n = 6 err = <nil> b = [101 97 100 101 114 33 32 82]
b[:n] = "eader!"
n = 0 err = EOF b = [101 97 100 101 114 33 32 82]
b[:n] = ""

```

**Comment by OlingCat** [comment]
啊，感谢指正，the read end of a stream of data 是指数据流的读取端。

**Comment by yangyangnote** [comment]
可能这句话改成 io 包指定了 io.Reader 接口，它表示从数据流处进行读取。更好理解

**Comment by OlingCat** [comment]
新版已前移至 https://github.com/Go-zh/website
