### ISSUE TITLE
"切片的长度与容量" 两个问题

### ISSUE THREAD

**Issue by yangyangnote** [Go-zh/tour#362]
上下文 
https://tour.go-zh.org/moretypes/11
第一个问题
原切片为s := []int{2, 3, 5, 7, 11, 13}
从
(1)s = s[:4]
printSlice(s)
到
(2)s = s[2:]
printSlice(s)
输出的结果来看
(1)是在原切片基础上切的
(2)是在(1)的基础上切的
这个逻辑应该是对的,但矛盾的是在这两个赋值之前
s = s[:0]
printSlice(s)
已经切过一次了,后两个应该在 [] 基础上切才对,但是[] 这里已经没值了，为什么后面还能继续切?

第二个问题
从(1)到(2) cap(容量)为什么突然从6变成4,感觉没有什么规律?

**Comment by OlingCat** [comment]
（1）所有的切片都有一个底层数组，切片只是一对表示开始和结束的指针，因此无论基于哪个切片来切，底层数组都是不变的。
（2）切片的容量是它的长度加上其底层数组剩余的长度。容量会根据可能的需要自动分配，不够时就会复制一份再扩容。
具体细节详见 https://go-zh.org/ref/spec.old#%E5%88%87%E7%89%87%E7%B1%BB%E5%9E%8B

**Comment by yangyangnote** [comment]
(1) 这个例子中的底层数组是什么呢?应该是{2, 3, 5, 7, 11, 13}? 如果这个是基本数组的话,s[:0],s[:4],s[2:]应该都是在这个数组的基础上切的,那么 ,s[:0],s[:4] 是符合这一逻辑的 但明显s[2:]是在s[:4]的基础上切的,所以结果为[5 7],如果是在{2, 3, 5, 7, 11, 13} 基础上切的话 按照 s[2:] 大于等于第二个位置来看,结果应该为 [5,7,11,13]才对。为什会是[5 7]?

**Comment by s1eke** [comment]
我也遇到了这样的困惑，看到大佬的解答后我有点明白了。

> 切片只是一对表示开始和结束的指针

所以
s = s[:0]的时候开始和结束指针都指向s[0]
s = s[:4]的时候没有设置上界值，切片的开始指针没有变化，还是指向s[:0]的上界也就是s[0]
s = s[2:]的时候，开始指针指向s[2]，而下界没有设置，所以结束指针没有变化，还是指向s[:4]的下界也就是s[4]

**Comment by OlingCat** [comment]
新编已迁移至 https://github.com/Go-zh/website ，稍后会更新。
