### ISSUE TITLE
与英文不一致无法运行playground

### ISSUE THREAD

**Issue by gaoxingliang** [Go-zh/tour#366]
上下文: https://tour.go-zh.org/welcome/3
 

> 本指南也可作为独立的程序使用，这样你无需访问互联网就能运行它。 独立的 tour 更快，它会在你自己的机器上构建并运行代码示例。 要在本地安装并运行此教程的中文版，请在命令行执行： go get -u github.com/Go-zh/tour tour

这里English 版本是:
> To run the tour locally install and run the tour binary:
```
go get golang.org/x/tour
tour
```
但是依然无法运行
https://tour.golang.org/welcome/3

**Comment by OlingCat** [comment]
由于 `go mod` 的使用导致无法完全脱离 `golang.org/x`，也就意味着没有办法不翻墙就能安装了，因此要在本地安装只能走代理。

**Comment by gaoxingliang** [comment]
这里需要不改变原来的url才行. 因为`go get golang.org/x/tour`才是正确的url. 而不是 `go get -u github.com/Go-zh/tour`  因为没有go-zh这个.  当然 确实需要FQ.

**Comment by OlingCat** [comment]
新版已迁移至 https://github.com/Go-zh/website
