### ISSUE TITLE
Error communicating with remote server

### ISSUE THREAD

**Issue by Dounx** [Go-zh/tour#367]
运行代码：[Hello, 世界](http://go-tour-zh.appspot.com/welcome/1) 的示例代码，其他的章节结果也一样。

表单数据正常提交。

Post URL: http://go-tour-zh.appspot.com/compile
Response Code: 200 OK
Return Content: Bad Request

本地端运行正常。

**Comment by OlingCat** [comment]
这个很早就废弃了，请使用 tour.go-zh.org
