### ISSUE TITLE
参考链接失效

### ISSUE THREAD

**Issue by wan223** [Go-zh/tour#376]
https://blog.go-zh.org/gos-declaration-syntax链接失效

上下文：
函数
函数可以没有参数或接受多个参数。

在本例中，add 接受两个 int 类型的参数。

注意类型在变量名 之后。

（参考 这篇关于 Go 语法声明的文章了解这种类型声明形式出现的原因。）《《《----

**Comment by OlingCat** [comment]
呃....年久失修的 blog 已经挂了，你要想看可以先看凑合看这里：https://github.com/Go-zh/go-zh.github.io.old/blob/master/zh-articles/gos_declaration_syntax.html

**Comment by wan223** [comment]
感谢感谢
