### ISSUE TITLE
没有英文版本的链接

### ISSUE THREAD

**Issue by yeqing-lux** [Go-zh/tour#377]
上下文: https://tour.go-zh.org/welcome/2

在这一页中没有 English 版本的链接，没办法切换到英文版。（对比法文版网页中是有英文版链接的）
<img width="1010" alt="截屏 4" src="https://user-images.githubusercontent.com/32286588/72869808-50617200-3d21-11ea-905c-ece5ca27d7bd.png">

**Comment by OlingCat** [comment]
啊..确实之后会补上。
不过英文版就是官方网站的链接了，应该很好找。

Qing Ye <notifications@github.com> 于 2020年1月22日周三 14:02写道：

**Comment by yeqing-lux** [comment]
嗯嗯！找起来是很容易。只是现在的排版如果用户如果想要看英文版会很困惑，我那天就找了几分钟才意识到没有: )


在2020年01月23日 23:19，Oling Cat 写道：
啊..确实之后会补上。
不过英文版就是官方网站的链接了，应该很好找。

Qing Ye <notifications@github.com> 于 2020年1月22日周三 14:02写道：

**Comment by OlingCat** [comment]
新版已迁移至 https://github.com/Go-zh/website
