### ISSUE TITLE
"dereferencing" or "indirecting" 这句话的翻译问题

### ISSUE THREAD

**Issue by yeqing-lux** [Go-zh/tour#379]
上下文: https://tour.go-zh.org/moretypes/1
将 dereferencing 和 indirecting 中文翻译成 “‘间接引用’或‘重定向’” 感觉有问题。

- 我参考了这个[博客](https://zhuanlan.zhihu.com/p/27376610)，dereferencing指的是“解引用“或者“引用解析”。

- indirecting 应该是 “间接引用”。

这里只是提出我的一些看法，不一定正确， 仅做参考：）

**Comment by OlingCat** [comment]
感谢，你的翻译是对的

**Comment by OlingCat** [comment]
新版已前移至 https://github.com/Go-zh/website
