### ISSUE TITLE
Unix时间戳返回不准time.Now().Unix())

### ISSUE THREAD

**Issue by zhoulipeng** [Go-zh/tour#383]
上下文: https://tour.go-zh.org/welcome/1

源代码如下：
---------------------------------------------

package main

import "fmt"
import "time"

func main() {
	fmt.Println("Hello, 世界")
	fmt.Println(time.Now().Unix())
}

---------------------------一段时间内总是输出同一个整数------------------
Hello, 世界
125789000

**Comment by OlingCat** [comment]
服务器的返回时间是固定的。
