### ISSUE TITLE
译注有问题

### ISSUE THREAD

**Issue by zhibinwang1996** [Go-zh/tour#387]
上下文: https://tour.go-zh.org/methods/3
内建类型也可以声明方法
package main

import (
	"fmt"
	"math"
)

type MyFloat float64
type MyInt int64

func (f MyFloat) Abs() float64 {
	if f < 0 {
		return float64(-f)
	}
	return float64(f)
}
func (num MyInt) fun1(){
	println("test")
}

func main() {
	f := MyFloat(-math.Sqrt2)
	fmt.Println(f.Abs())
	x:=MyInt(1)
	x.fun1()
}

**Comment by OlingCat** [comment]
感谢指正，已修改。新编已迁移至 https://github.com/Go-zh/website ，稍后会更新。
