### ISSUE TITLE
[翻译错误，有误导]

### ISSUE THREAD

**Issue by frihed** [Go-zh/tour#407]
上下文: https://tour.go-zh.org/concurrency/4

原英文：
Note: Only the sender should close a channel, never the receiver. Sending on a closed channel will cause a panic.

当前页面：
*注意：* 只有发送者才能关闭信道，而接收者不能。向一个已经关闭的信道发送数据会引发程序恐慌（panic）。

修改意见：
**注意**： 只应该由发送方关闭信道，而不应该由接收方，向一个已经关闭的信道发送数据会引发程序恐慌（panic）。

--------
原因说明： 接收方也能关闭信道，是不为也，非不能也。

**Comment by OlingCat** [comment]
感谢指正。新版已迁移至 https://github.com/Go-zh/website
