### ISSUE TITLE
package golang.org/x/net/websocket: unrecognized import path "golang.org/x/net/websocket"

### ISSUE THREAD

**Issue by Kyrie-W** [Go-zh/tour#408]
（如果安装过程中出现 package 或 import 字样的错误提示，那么说明依赖库的导入路径又挂了。这时请猛戳 @OlingCat 并督促其解决= =||）

**Comment by OlingCat** [comment]
新编已迁移至 https://github.com/Go-zh/website ，稍后会更新。
