### ISSUE TITLE
文本介绍格式错误

### ISSUE THREAD

**Issue by ai1urus** [Go-zh/tour#413]
上下文: https://tour.go-zh.org/concurrency/4

![image](https://user-images.githubusercontent.com/23050548/139401734-5b0a0d72-72a5-491d-98d6-0a1274ca1366.png)

其中 *注意：*  和 *还要注意：* 应该是粗体，这里格式并没有显示出来。

**Comment by OlingCat** [comment]
已修复。新版已迁移至 https://github.com/Go-zh/website
