### ISSUE TITLE
执行以后提示 too many arguments to return

### ISSUE THREAD

**Issue by Ruiching** [Go-zh/tour#417]
上下文: http://tour.studygolang.com/flowcontrol/5

请修改上方的标题来简要描述要汇报的问题，并把详细的内容写在这里，如果可能的话请附上源代码

错误位置：return fmt.Sprint(math.Sqrt(x))

修改后：log := fmt.Sprintf("%f", math.Sqrt(x))
	          return log

**Comment by OlingCat** [comment]
新版已迁移至 https://github.com/Go-zh/website
