### ISSUE TITLE
是不是go 的依赖库导入错了

### ISSUE THREAD

**Issue by zsp108** [Go-zh/tour#419]
执行go get -u github.com/Go-zh/tour出现以下提示，前面下载好好的，但是后面出现go install pkg@version

go: downloading golang.org/x/net v0.0.0-20190313220215-9f648a60d977
go: downloading golang.org/x/net v0.0.0-20211216030914-fe4d6282115f
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

@OlingCat

**Comment by OlingCat** [comment]
新版已迁移至 https://github.com/Go-zh/website
