### ISSUE TITLE
关于*的渲染问题

### ISSUE THREAD

**Issue by AHBICJ** [Go-zh/tour#424]
content/methods.article L176
```指定了零个方法的接口值被称为 *空接口：*```
(1) *没有被渲染成斜体(或别的页面实际表现的加粗), 些微影响阅读
(2) 不管渲染的话, 个人理解也应该是```*空接口*：```
<img width="453" alt="image" src="https://user-images.githubusercontent.com/31472450/168944244-54be46a2-a14c-437b-9dfd-0bce1f2680d7.png">

原文:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/31472450/168944074-30887a60-352f-4859-9139-11374f683c27.png">

**Comment by OlingCat** [comment]
新版已迁移至 https://github.com/Go-zh/website
