### ISSUE TITLE
已经不能通过go get -u安装，通过go install安装后本地运行显示为英文原版，未显示简体中文

### ISSUE THREAD

**Issue by nikola-chen** [Go-zh/tour#426]
已经不能通过go get -u安装，通过go install安装后本地运行，可以通过http://127.0.0.1:3999/tour/welcome/1
访问，但是显示内容为英文原版，未显示简体中文内容
环境 MacOS 12.4，go1.18.3

**Comment by OlingCat** [comment]
新编已迁移至 https://github.com/Go-zh/website ，稍后会更新。
