### ISSUE TITLE
页面汉字拼写错误

### ISSUE THREAD

**Issue by sagiriiiiii** [Go-zh/tour#432]
上下文: https://tour.go-zh.org/methods/4
![image](https://user-images.githubusercontent.com/45867624/190360515-557d6049-15f6-4347-ac15-b5ab45acfab1.png)
最后一行指针接收者写成了指针接受者

**Comment by OlingCat** [comment]
感谢指正。新编已迁移至 https://github.com/Go-zh/website ，稍后会更新。
