### ISSUE TITLE
离线版教程里，与官网不一致，应该用go install指令

### ISSUE THREAD

**Issue by DengYuncheng27** [Go-zh/tour#436]
上下文: https://tour.go-zh.org/welcome/3

### Go 离线版教程
本指南也可作为独立的程序使用，这样你无需访问互联网就能运行它。 独立的 tour 更快，它会在你自己的机器上构建并运行代码示例。 要在本地安装并运行此教程的中文版，请在命令行执行： go get -u github.com/Go-zh/tour tour
由于get指令更新后？ 总之这个并不会在GOPATH/bin路径下生成对应的程序，，看官网描述是需要一个类似这样的`go install golang.org/x/website/tour@latest` go install command。 然后去运行GOPATH/bin路径下的二进制文件

**Comment by OlingCat** [comment]
新编已迁移至 https://github.com/Go-zh/website ，稍后会更新。
