### ISSUE TITLE
中文版本的包章节存在过时内容

### ISSUE THREAD

**Issue by rurumuri** [Go-zh/tour#441]
上下文: https://tour.go-zh.org/basics/1

原文：“*注意：* 此程序的运行环境是固定的，因此 rand.Intn 总是会返回相同的数字。 （要得到不同的数字，需为生成器提供不同的种子数，参见 [rand.Seed](https://go-zh.org/pkg/math/rand/#Seed)。 练习场中的时间为常量，因此你需要用其它的值作为种子数。）”

在最新的Go版本中，`rand.Seed()`已弃用，`rand.Intn()`可以直接按预期工作

**Comment by OlingCat** [comment]
感谢建议，新版已迁移至 https://github.com/Go-zh/website ，稍后会更新。
