### ISSUE TITLE
[切片的长度与容量一节的中文说明有问题]

### ISSUE THREAD

**Issue by yfliu-beerman** [Go-zh/tour#442]
上下文: https://tour.go-zh.org/moretypes/11

”试着修改示例程序中的切片操作，向外扩展它的容量，看看会发生什么“ 应该改为
”试着修改示例程序中的切片操作，向外扩展它的长度，看看会发生什么“

**Comment by OlingCat** [comment]
感谢建议，已在新版中修正，稍后会更新到 https://github.com/Go-zh/website
