### ISSUE TITLE
Windows 环境下使用 `go get -u github.com/Go-zh/tour` 并没有在 `$GOPATH/bin` 下创建二进制文件 `tour.exe`

### ISSUE THREAD

**Issue by RaspStudio** [Go-zh/tour#444]
按 readme 里面的指令试了好几次也没有二进制文件，困惑了一会儿，最后直接在仓库目录 `go build` 了，是否考虑修改一下 readme

- 环境
  - Windows 11
  - go version go1.21.4 windows/amd64

本以为本地版可以在本地编译能快一点没想到还是要用 playground

**Comment by ngbenci** [comment]
报错信息是啥？我是把错误提示中的包，下载到本地，然后install，就可以了。
